services:
    metamodels.filter_perimetersearch.factory:
        class: MetaModels\FilterPerimetersearchBundle\FilterSetting\PerimetersearchFilterSettingTypeFactory
        arguments:
            - '@event_dispatcher'
            - '@database_connection'
            - '@MetaModels\Filter\FilterUrlBuilder'
        tags:
            - { name: metamodels.filter_factory }
