services:
    metamodels.filter_perimetersearch.listener.filter_setting_renderer:
        class: MetaModels\FilterPerimetersearchBundle\EventListener\PerimeterFilterSettingTypeRendererListener
        public: true
        arguments:
            - "@metamodels.filter_setting_factory"
            - "@event_dispatcher"
            - "@metamodels.assets.icon_builder"
            - "@cca.dc-general.scope-matcher"
        tags:
            -   name: kernel.event_listener
                event: 'dc-general.view.contao2backend.model-to-label'
                method: modelToLabel

    MetaModels\FilterPerimetersearchBundle\EventListener\DcGeneral\Table\FilterSetting\AttributeListener:
        public: true
        arguments:
            - "@metamodels.filter_setting_factory"
            - '@MetaModels\CoreBundle\Formatter\SelectAttributeOptionLabelFormatter'
        tags:
            -   name: kernel.event_listener
                event: dc-general.view.contao2backend.get-property-options
                method: getOptions

    metamodels.dc_general.table.tl_metamodel_filtersetting.range_template:
        class: MetaModels\FilterPerimetersearchBundle\EventListener\DcGeneral\Table\FilterSetting\Templates
        public: true
        arguments:
            - "@metamodels.template_list"
            - "@metamodels.filter_setting_factory"
        tags:
            -   name: kernel.event_listener
                event: dc-general.view.contao2backend.get-property-options
                method: getOptions

    metamodels.dc_general.table.tl_metamodel_filtersetting.lookupservice:
        class: MetaModels\FilterPerimetersearchBundle\EventListener\DcGeneral\Table\FilterSetting\LookupServiceListener
        public: true
        arguments:
            - "@metamodels.filter_setting_factory"
            - "@contao.translation.translator"
        tags:
            -   name: kernel.event_listener
                event: men-at-work.multi-column-wizard.get-options
                method: getOptions

    MetaModels\FilterPerimetersearchBundle\EventListener\SetDefaultRangeSelectionListener:
        public: true
        tags:
            -   name: kernel.event_listener
                event: dc-general.model.pre-persist
                method: __invoke
